// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'bc473b59f0ce2674b8cbec403f4949680d998c3aef46b8c39cb2bd5cd75bbed3'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Department: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly parentId: CodecTypes['pg/int4@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Equipment: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly type:
        | 'laptop'
        | 'desktop'
        | 'docking_station'
        | 'monitor'
        | 'printer'
        | 'iphone'
        | 'ipad'
        | 'other';
      readonly brand: CodecTypes['pg/text@1']['output'];
      readonly model: CodecTypes['pg/text@1']['output'] | null;
      readonly serialNumber: CodecTypes['pg/text@1']['output'];
      readonly status: 'in_storage' | 'reserved' | 'handed_out' | 'awaiting_repair' | 'retired';
      readonly departmentId: CodecTypes['pg/int4@1']['output'] | null;
      readonly currentHolderId: CodecTypes['pg/int4@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly EquipmentEvent: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly type: 'intake' | 'return' | 'handout';
      readonly equipmentId: CodecTypes['pg/int4@1']['output'];
      readonly visitId: CodecTypes['pg/int4@1']['output'];
      readonly chargerIncluded: CodecTypes['pg/bool@1']['output'];
      readonly otherAccessoriesIncluded: CodecTypes['pg/bool@1']['output'];
      readonly accessoryNotes: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly EquipmentVisit: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly status: 'draft' | 'completed';
      readonly occurredAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly ticketNumber: CodecTypes['pg/text@1']['output'];
      readonly processedById: CodecTypes['pg/int4@1']['output'] | null;
      readonly counterpartyId: CodecTypes['pg/int4@1']['output'] | null;
      readonly counterpartyNote: CodecTypes['pg/text@1']['output'] | null;
      readonly signatureUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Staff: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'] | null;
      readonly azureAdId: CodecTypes['pg/text@1']['output'] | null;
      readonly status: 'active' | 'on_leave' | 'resigned';
      readonly departmentId: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Department: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly parentId: CodecTypes['pg/int4@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Equipment: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly type:
        | 'laptop'
        | 'desktop'
        | 'docking_station'
        | 'monitor'
        | 'printer'
        | 'iphone'
        | 'ipad'
        | 'other';
      readonly brand: CodecTypes['pg/text@1']['input'];
      readonly model: CodecTypes['pg/text@1']['input'] | null;
      readonly serialNumber: CodecTypes['pg/text@1']['input'];
      readonly status: 'in_storage' | 'reserved' | 'handed_out' | 'awaiting_repair' | 'retired';
      readonly departmentId: CodecTypes['pg/int4@1']['input'] | null;
      readonly currentHolderId: CodecTypes['pg/int4@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly EquipmentEvent: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly type: 'intake' | 'return' | 'handout';
      readonly equipmentId: CodecTypes['pg/int4@1']['input'];
      readonly visitId: CodecTypes['pg/int4@1']['input'];
      readonly chargerIncluded: CodecTypes['pg/bool@1']['input'];
      readonly otherAccessoriesIncluded: CodecTypes['pg/bool@1']['input'];
      readonly accessoryNotes: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly EquipmentVisit: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly status: 'draft' | 'completed';
      readonly occurredAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly ticketNumber: CodecTypes['pg/text@1']['input'];
      readonly processedById: CodecTypes['pg/int4@1']['input'] | null;
      readonly counterpartyId: CodecTypes['pg/int4@1']['input'] | null;
      readonly counterpartyNote: CodecTypes['pg/text@1']['input'] | null;
      readonly signatureUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Staff: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'] | null;
      readonly azureAdId: CodecTypes['pg/text@1']['input'] | null;
      readonly status: 'active' | 'on_leave' | 'resigned';
      readonly departmentId: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly department: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly parentId: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly equipment: {
      readonly brand: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly currentHolderId: CodecTypes['pg/int4@1']['output'] | null;
      readonly departmentId: CodecTypes['pg/int4@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly model: CodecTypes['pg/text@1']['output'] | null;
      readonly serialNumber: CodecTypes['pg/text@1']['output'];
      readonly status: 'in_storage' | 'reserved' | 'handed_out' | 'awaiting_repair' | 'retired';
      readonly type:
        | 'laptop'
        | 'desktop'
        | 'docking_station'
        | 'monitor'
        | 'printer'
        | 'iphone'
        | 'ipad'
        | 'other';
    };
    readonly equipmentEvent: {
      readonly accessoryNotes: CodecTypes['pg/text@1']['output'] | null;
      readonly chargerIncluded: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly equipmentId: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly otherAccessoriesIncluded: CodecTypes['pg/bool@1']['output'];
      readonly type: 'intake' | 'return' | 'handout';
      readonly visitId: CodecTypes['pg/int4@1']['output'];
    };
    readonly equipmentVisit: {
      readonly counterpartyId: CodecTypes['pg/int4@1']['output'] | null;
      readonly counterpartyNote: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly occurredAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly processedById: CodecTypes['pg/int4@1']['output'] | null;
      readonly signatureUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly status: 'draft' | 'completed';
      readonly ticketNumber: CodecTypes['pg/text@1']['output'];
    };
    readonly staff: {
      readonly azureAdId: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly departmentId: CodecTypes['pg/int4@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly status: 'active' | 'on_leave' | 'resigned';
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly department: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly parentId: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly equipment: {
      readonly brand: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly currentHolderId: CodecTypes['pg/int4@1']['input'] | null;
      readonly departmentId: CodecTypes['pg/int4@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly model: CodecTypes['pg/text@1']['input'] | null;
      readonly serialNumber: CodecTypes['pg/text@1']['input'];
      readonly status: 'in_storage' | 'reserved' | 'handed_out' | 'awaiting_repair' | 'retired';
      readonly type:
        | 'laptop'
        | 'desktop'
        | 'docking_station'
        | 'monitor'
        | 'printer'
        | 'iphone'
        | 'ipad'
        | 'other';
    };
    readonly equipmentEvent: {
      readonly accessoryNotes: CodecTypes['pg/text@1']['input'] | null;
      readonly chargerIncluded: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly equipmentId: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly otherAccessoriesIncluded: CodecTypes['pg/bool@1']['input'];
      readonly type: 'intake' | 'return' | 'handout';
      readonly visitId: CodecTypes['pg/int4@1']['input'];
    };
    readonly equipmentVisit: {
      readonly counterpartyId: CodecTypes['pg/int4@1']['input'] | null;
      readonly counterpartyNote: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly occurredAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly processedById: CodecTypes['pg/int4@1']['input'] | null;
      readonly signatureUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly status: 'draft' | 'completed';
      readonly ticketNumber: CodecTypes['pg/text@1']['input'];
    };
    readonly staff: {
      readonly azureAdId: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly departmentId: CodecTypes['pg/int4@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly status: 'active' | 'on_leave' | 'resigned';
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly department: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly parentId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['name'] }];
              indexes: readonly [
                {
                  readonly name: 'department_parentId_idx_6a68f597';
                  readonly prefix: 'department_parentId_idx';
                  readonly columns: readonly ['parentId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'department';
                    readonly columns: readonly ['parentId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'department';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly equipment: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly brand: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'HP'>;
                  };
                };
                readonly model: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly serialNumber: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'in_storage'>;
                  };
                };
                readonly departmentId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly currentHolderId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['serialNumber'] }];
              indexes: readonly [
                {
                  readonly name: 'equipment_departmentId_idx_8e261ed8';
                  readonly prefix: 'equipment_departmentId_idx';
                  readonly columns: readonly ['departmentId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'equipment_currentHolderId_idx_f15564bd';
                  readonly prefix: 'equipment_currentHolderId_idx';
                  readonly columns: readonly ['currentHolderId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'equipment_status_idx_e98638ab';
                  readonly prefix: 'equipment_status_idx';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'equipment';
                    readonly columns: readonly ['departmentId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'department';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'equipment';
                    readonly columns: readonly ['currentHolderId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'staff';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly equipmentEvent: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly equipmentId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly visitId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly chargerIncluded: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly otherAccessoriesIncluded: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly accessoryNotes: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'equipmentEvent_equipmentId_idx_e1548594';
                  readonly prefix: 'equipmentEvent_equipmentId_idx';
                  readonly columns: readonly ['equipmentId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'equipmentEvent_type_idx_b6b604ea';
                  readonly prefix: 'equipmentEvent_type_idx';
                  readonly columns: readonly ['type'];
                  readonly unique: false;
                },
                {
                  readonly name: 'equipmentEvent_visitId_idx_fcfcb8fb';
                  readonly prefix: 'equipmentEvent_visitId_idx';
                  readonly columns: readonly ['visitId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'equipmentEvent';
                    readonly columns: readonly ['equipmentId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'equipment';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'equipmentEvent';
                    readonly columns: readonly ['visitId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'equipmentVisit';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly equipmentVisit: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'completed'>;
                  };
                };
                readonly occurredAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly ticketNumber: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly processedById: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly counterpartyId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly counterpartyNote: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly signatureUrl: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly notes: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'equipmentVisit_ticketNumber_idx_934212c9';
                  readonly prefix: 'equipmentVisit_ticketNumber_idx';
                  readonly columns: readonly ['ticketNumber'];
                  readonly unique: false;
                },
                {
                  readonly name: 'equipmentVisit_status_idx_e98638ab';
                  readonly prefix: 'equipmentVisit_status_idx';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
                {
                  readonly name: 'equipmentVisit_processedById_idx_92dfd8d4';
                  readonly prefix: 'equipmentVisit_processedById_idx';
                  readonly columns: readonly ['processedById'];
                  readonly unique: false;
                },
                {
                  readonly name: 'equipmentVisit_counterpartyId_idx_d3c53383';
                  readonly prefix: 'equipmentVisit_counterpartyId_idx';
                  readonly columns: readonly ['counterpartyId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'equipmentVisit';
                    readonly columns: readonly ['processedById'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'staff';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'equipmentVisit';
                    readonly columns: readonly ['counterpartyId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'staff';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly staff: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly azureAdId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'active'>;
                  };
                };
                readonly departmentId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['email'] },
                { readonly columns: readonly ['azureAdId'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'staff_departmentId_idx_8e261ed8';
                  readonly prefix: 'staff_departmentId_idx';
                  readonly columns: readonly ['departmentId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'staff';
                    readonly columns: readonly ['departmentId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'department';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly EquipmentEventType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['intake', 'return', 'handout'];
            };
            readonly EquipmentStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'in_storage',
                'reserved',
                'handed_out',
                'awaiting_repair',
                'retired',
              ];
            };
            readonly EquipmentType: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'laptop',
                'desktop',
                'docking_station',
                'monitor',
                'printer',
                'iphone',
                'ipad',
                'other',
              ];
            };
            readonly EquipmentVisitStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['draft', 'completed'];
            };
            readonly StaffStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['active', 'on_leave', 'resigned'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly department: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Department';
    };
    readonly staff: { readonly namespace: 'public' & NamespaceId; readonly model: 'Staff' };
    readonly equipment: { readonly namespace: 'public' & NamespaceId; readonly model: 'Equipment' };
    readonly equipmentVisit: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'EquipmentVisit';
    };
    readonly equipmentEvent: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'EquipmentEvent';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Department: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly parentId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly children: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Department';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['parentId'];
                };
              };
              readonly equipment: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Equipment';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['departmentId'];
                };
              };
              readonly parent: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Department';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['parentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly staff: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Staff';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['departmentId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'department';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly parentId: { readonly column: 'parentId' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly Equipment: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly brand: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly model: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly serialNumber: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly departmentId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly currentHolderId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly currentHolder: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Staff';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['currentHolderId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly department: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Department';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['departmentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly events: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'EquipmentEvent';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['equipmentId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'equipment';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly type: { readonly column: 'type' };
                readonly brand: { readonly column: 'brand' };
                readonly model: { readonly column: 'model' };
                readonly serialNumber: { readonly column: 'serialNumber' };
                readonly status: { readonly column: 'status' };
                readonly departmentId: { readonly column: 'departmentId' };
                readonly currentHolderId: { readonly column: 'currentHolderId' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly EquipmentEvent: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly equipmentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly visitId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly chargerIncluded: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly otherAccessoriesIncluded: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly accessoryNotes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly equipment: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Equipment';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['equipmentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly visit: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'EquipmentVisit';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['visitId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'equipmentEvent';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly type: { readonly column: 'type' };
                readonly equipmentId: { readonly column: 'equipmentId' };
                readonly visitId: { readonly column: 'visitId' };
                readonly chargerIncluded: { readonly column: 'chargerIncluded' };
                readonly otherAccessoriesIncluded: { readonly column: 'otherAccessoriesIncluded' };
                readonly accessoryNotes: { readonly column: 'accessoryNotes' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly EquipmentVisit: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly occurredAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly ticketNumber: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly processedById: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly counterpartyId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly counterpartyNote: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly signatureUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly notes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly counterparty: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Staff';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['counterpartyId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly items: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'EquipmentEvent';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['visitId'];
                };
              };
              readonly processedBy: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Staff';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['processedById'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'equipmentVisit';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly status: { readonly column: 'status' };
                readonly occurredAt: { readonly column: 'occurredAt' };
                readonly ticketNumber: { readonly column: 'ticketNumber' };
                readonly processedById: { readonly column: 'processedById' };
                readonly counterpartyId: { readonly column: 'counterpartyId' };
                readonly counterpartyNote: { readonly column: 'counterpartyNote' };
                readonly signatureUrl: { readonly column: 'signatureUrl' };
                readonly notes: { readonly column: 'notes' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly Staff: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly azureAdId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly departmentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly counterpartyVisits: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'EquipmentVisit';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['counterpartyId'];
                };
              };
              readonly department: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Department';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['departmentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly heldEquipment: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Equipment';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['currentHolderId'];
                };
              };
              readonly processedVisits: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'EquipmentVisit';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['processedById'];
                };
              };
            };
            readonly storage: {
              readonly table: 'staff';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly email: { readonly column: 'email' };
                readonly azureAdId: { readonly column: 'azureAdId' };
                readonly status: { readonly column: 'status' };
                readonly departmentId: { readonly column: 'departmentId' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
        };
        readonly enum: {
          readonly StaffStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'active'; readonly value: 'active' },
              { readonly name: 'on_leave'; readonly value: 'on_leave' },
              { readonly name: 'resigned'; readonly value: 'resigned' },
            ];
          };
          readonly EquipmentType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'laptop'; readonly value: 'laptop' },
              { readonly name: 'desktop'; readonly value: 'desktop' },
              { readonly name: 'docking_station'; readonly value: 'docking_station' },
              { readonly name: 'monitor'; readonly value: 'monitor' },
              { readonly name: 'printer'; readonly value: 'printer' },
              { readonly name: 'iphone'; readonly value: 'iphone' },
              { readonly name: 'ipad'; readonly value: 'ipad' },
              { readonly name: 'other'; readonly value: 'other' },
            ];
          };
          readonly EquipmentStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'in_storage'; readonly value: 'in_storage' },
              { readonly name: 'reserved'; readonly value: 'reserved' },
              { readonly name: 'handed_out'; readonly value: 'handed_out' },
              { readonly name: 'awaiting_repair'; readonly value: 'awaiting_repair' },
              { readonly name: 'retired'; readonly value: 'retired' },
            ];
          };
          readonly EquipmentEventType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'intake'; readonly value: 'intake' },
              { readonly name: 'return'; readonly value: 'return' },
              { readonly name: 'handout'; readonly value: 'handout' },
            ];
          };
          readonly EquipmentVisitStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'draft'; readonly value: 'draft' },
              { readonly name: 'completed'; readonly value: 'completed' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
